<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MaleFemaleOther</name>
   <tag></tag>
   <elementGuidId>7578d8d9-0b75-498d-8bc2-5d2c00d9785c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#genterWrapper > div.col-md-9.col-sm-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='genterWrapper']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>062792da-968a-42f2-aa2d-1e29d7c60518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-9 col-sm-12</value>
      <webElementGuid>35867735-b988-429f-9f24-74c75e16eae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MaleFemaleOther</value>
      <webElementGuid>520918f9-85ee-4ea4-aae0-c68af08baadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;genterWrapper&quot;)/div[@class=&quot;col-md-9 col-sm-12&quot;]</value>
      <webElementGuid>af5d3ef3-f66a-4dfa-afe9-fcaabe8990e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='genterWrapper']/div[2]</value>
      <webElementGuid>5ca6a698-f8a3-4b76-b221-47654a38f8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::div[1]</value>
      <webElementGuid>ebacb115-46e2-4ea6-b8c2-0da02a9e8c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[4]</value>
      <webElementGuid>d2ac89de-9a25-4a7e-80a8-6c80097e0137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>9bf98115-8939-4acb-87ca-564405943387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MaleFemaleOther' or . = 'MaleFemaleOther')]</value>
      <webElementGuid>a612afe8-5ab9-482f-b1ad-ffe9eb70ab67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
